[workspace]
members = [
    "exonum",
    "crypto",
    "testkit",
    "testkit/server",
    "services/configuration",
    "services/time",
    "examples/demo-create-service-cryptocurrency",
    "examples/demo-create-service-with-data-proofs/backend",
    "examples/demo-create-service-timestamping/backend",
]
exclude = [ "exonum/fuzz" ]
