[workspace]
members = [
    "exonum",
    "crypto",
    "testkit",
    "testkit/server",
    "services/configuration",
    "services/time",
    "examples/demo-service",
    "examples/demo-data-proofs/backend",
    "examples/demo-timestamping/backend",
]
exclude = [ "exonum/fuzz" ]
